#!/usr/bin/env python3
"""Interactive setup: asks for each API key (hidden input), finds the Telegram chat ID,
and writes everything to .env. Standard library only — runs on macOS's Python 3.9."""

import getpass
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"
CHAT_ID_WAIT_SECONDS = 180

# Order here is the order written to .env
ENV_KEYS = [
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_BOT_USERNAME",
    "TELEGRAM_CHAT_ID",
    "SUPABASE_URL",
    "SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_SECRET_KEY",
    "ANTHROPIC_API_KEY",
    "GMAIL_CREDENTIALS_PATH",
    "GMAIL_TOKEN_PATH",
]
DEFAULTS = {
    "GMAIL_CREDENTIALS_PATH": "config/credentials.json",
    "GMAIL_TOKEN_PATH": "config/token.json",
}

VALIDATORS = {
    "TELEGRAM_BOT_TOKEN": re.compile(r"^\d{6,12}:[A-Za-z0-9_-]{30,}$"),
    "TELEGRAM_CHAT_ID": re.compile(r"^-?\d{3,20}$"),
    "SUPABASE_URL": re.compile(r"^https://[a-z0-9-]+\.supabase\.co$"),
    "SUPABASE_PUBLISHABLE_KEY": re.compile(r"^(sb_publishable_\S+|eyJ\S+)$"),
    "SUPABASE_SECRET_KEY": re.compile(r"^(sb_secret_\S+|eyJ\S+)$"),
    "ANTHROPIC_API_KEY": re.compile(r"^sk-ant-\S{20,}$"),
}

PROMPTS = [
    {
        "key": "TELEGRAM_BOT_TOKEN",
        "title": "טוקן של בוט הטלגרם",
        "help": [
            "בטלגרם: פתחי שיחה עם ‎@BotFather ← שלחי ‎/mybots ← בחרי את הבוט שלך",
            "← לחצי ‎API Token‎ ← העתיקי את הטוקן (נראה כמו ‎123456789:AAH...‎).",
        ],
        "secret": True,
    },
    {
        "key": "SUPABASE_URL",
        "title": "כתובת הפרויקט ב-Supabase ‏(Project URL)",
        "help": [
            "ב-supabase.com: היכנסי לפרויקט ← ‎Project Settings‎ (גלגל שיניים למטה משמאל)",
            "← ‎Data API‎ ← העתיקי את ‎Project URL‎ (נראה כמו ‎https://abcd1234.supabase.co‎).",
        ],
        "secret": False,
    },
    {
        "key": "SUPABASE_PUBLISHABLE_KEY",
        "title": "המפתח הציבורי של Supabase ‏(Publishable key)",
        "help": [
            "ב-Supabase: ‎Project Settings ← API Keys‎ ← העתיקי את ה-‎Publishable key",
            "(מתחיל ב-‎sb_publishable_‎).",
        ],
        "secret": True,
    },
    {
        "key": "SUPABASE_SECRET_KEY",
        "title": "המפתח הסודי של Supabase ‏(Secret key)",
        "help": [
            "באותו מסך ‎API Keys‎ ← תחת ‎Secret keys‎ לחצי על סמל העין/העתקה",
            "(מתחיל ב-‎sb_secret_‎). זה מפתח עם גישה מלאה — לא לשתף עם אף אחד.",
        ],
        "secret": True,
    },
    {
        "key": "ANTHROPIC_API_KEY",
        "title": "מפתח Claude API",
        "help": [
            "ב-console.anthropic.com ← ‎API Keys‎ ← ‎Create Key‎ ← העתיקי (מתחיל ב-‎sk-ant-‎).",
            "המפתח מוצג רק פעם אחת — אם איבדת אותו, צרי חדש.",
        ],
        "secret": True,
    },
]


# ------------------------------------------------------------------ .env helpers
def parse_env(text):
    """Parse KEY=VALUE lines; ignores comments and blank lines."""
    values = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        values[key.strip()] = value
    return values


def read_env(path=ENV_PATH):
    path = Path(path)
    if not path.exists():
        return {}
    return parse_env(path.read_text(encoding="utf-8"))


def render_env(values):
    lines = ["# FirstIn secrets — generated by scripts/setup_env.py. NEVER commit this file.", ""]
    for key in ENV_KEYS:
        lines.append("{}={}".format(key, values.get(key, "")))
    for key in sorted(k for k in values if k not in ENV_KEYS):
        lines.append("{}={}".format(key, values[key]))
    return "\n".join(lines) + "\n"


def write_env(values, path=ENV_PATH):
    """Write .env with owner-only permissions (600)."""
    path = Path(path)
    fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(render_env(values))
    os.chmod(str(path), 0o600)


def normalize(key, value):
    value = value.strip()
    if key == "SUPABASE_URL":
        value = value.rstrip("/")
    return value


def is_valid(key, value):
    pattern = VALIDATORS.get(key)
    return bool(value) and (pattern is None or bool(pattern.match(value)))


# ------------------------------------------------------------------ Telegram helpers
def telegram_call(token, method, params=None, timeout=40):
    url = "https://api.telegram.org/bot{}/{}".format(token, method)
    data = json.dumps(params or {}).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        try:
            return json.loads(e.read().decode("utf-8"))
        except ValueError:
            return {"ok": False, "description": "HTTP {}".format(e.code)}


def extract_private_chat(updates):
    """Return (chat_id, first_name) of the latest private-chat message, or (None, None)."""
    for update in reversed(updates):
        msg = update.get("message") or update.get("edited_message")
        if not msg:
            continue
        chat = msg.get("chat", {})
        if chat.get("type") == "private" and "id" in chat:
            return chat["id"], chat.get("first_name", "")
    return None, None


def latest_update_id(updates):
    return max((u.get("update_id", 0) for u in updates), default=None)


# ------------------------------------------------------------------ UI
def say(text=""):
    print(text, flush=True)


def header(step, total, title):
    say()
    say("─" * 60)
    say("שלב {}/{} · {}".format(step, total, title))
    say("─" * 60)


def ask_yes_no(question, default=True):
    suffix = " [Y/n] " if default else " [y/N] "
    while True:
        answer = input(question + suffix).strip().lower()
        if not answer:
            return default
        if answer in ("y", "yes", "כ", "כן"):
            return True
        if answer in ("n", "no", "ל", "לא"):
            return False


def prompt_value(item, existing):
    key = item["key"]
    for line in item["help"]:
        say("  " + line)
    if item["secret"]:
        say("  (ההקלדה מוסתרת — לא יופיע כלום על המסך, זה תקין. הדביקי עם ‎Cmd+V‎ ולחצי ‎Enter‎.)")
    if existing:
        say("  ✓ כבר יש ערך שמור. לחיצה על ‎Enter‎ בלי להקליד כלום = להשאיר אותו.")

    while True:
        label = "  ‎{}: ".format(key)
        raw = getpass.getpass(label) if item["secret"] else input(label)
        value = normalize(key, raw)
        if not value:
            if existing:
                say("  ← נשאר הערך הקיים.")
                return existing
            say("  ✗ לא הוזן כלום, נסי שוב.")
            continue
        if is_valid(key, value):
            if item["secret"]:
                say("  ✓ נקלטו {} תווים.".format(len(value)))
            return value
        say("  ⚠ הערך לא נראה בפורמט הצפוי.")
        if not ask_yes_no("  לשמור בכל זאת? (n = להקליד שוב)", default=False):
            continue
        return value


def verify_bot(token):
    """Returns the bot's username if Telegram accepts the token, False if rejected, None if offline."""
    say("  בודקת את הטוקן מול טלגרם...")
    try:
        res = telegram_call(token, "getMe", timeout=15)
    except Exception as e:  # network / SSL errors
        say("  ⚠ לא הצלחתי להתחבר לטלגרם ({}). אפשר להמשיך ולבדוק אחר כך.".format(e))
        return None
    if not res.get("ok"):
        say("  ✗ טלגרם דחה את הטוקן: {}".format(res.get("description", "")))
        return False
    username = res["result"].get("username", "")
    say("  ✓ הטוקן תקין — הבוט הוא ‎@{}‎.".format(username))
    return username


def find_chat_id(token, bot_username=""):
    """Ask the user to message the bot and long-poll getUpdates until a private message arrives."""
    try:
        initial = telegram_call(token, "getUpdates", {"timeout": 0}, timeout=15)
    except Exception as e:
        say("  ⚠ שגיאת רשת מול טלגרם: {}".format(e))
        return None
    if not initial.get("ok"):
        say("  ✗ טלגרם החזיר שגיאה: {}".format(initial.get("description", "")))
        if "webhook" in initial.get("description", "").lower():
            say("  (לבוט מוגדר webhook. אפשר להסיר אותו עם ‎deleteWebhook‎ — תגידי ל-Claude Code.)")
        return None
    last = latest_update_id(initial.get("result", []))
    offset = last + 1 if last is not None else None

    say()
    say("  👉 עכשיו: פתחי בטלגרם את ‎@{}‎ ושלחי לו הודעה כלשהי (למשל ‎/start‎).".format(bot_username or "הבוט שלך"))
    say("     אני מחכה עד {} דקות...".format(CHAT_ID_WAIT_SECONDS // 60))

    deadline = time.time() + CHAT_ID_WAIT_SECONDS
    while time.time() < deadline:
        params = {"timeout": 25, "allowed_updates": ["message", "edited_message"]}
        if offset is not None:
            params["offset"] = offset
        try:
            res = telegram_call(token, "getUpdates", params, timeout=35)
        except Exception:
            time.sleep(3)
            continue
        updates = res.get("result", []) if res.get("ok") else []
        if updates:
            offset = latest_update_id(updates) + 1
            chat_id, name = extract_private_chat(updates)
            if chat_id is not None:
                # Acknowledge the update so it isn't returned again
                try:
                    telegram_call(token, "getUpdates", {"offset": offset, "timeout": 0}, timeout=15)
                except Exception:
                    pass
                say("  ✓ קיבלתי הודעה{} — ה-chat ID נשמר.".format(" מ-" + name if name else ""))
                return str(chat_id)
        sys.stdout.write(".")
        sys.stdout.flush()
    say()
    say("  ⚠ לא הגיעה הודעה בזמן.")
    return None


def main():
    say("=" * 60)
    say("  FirstIn · הגדרת מפתחות")
    say("=" * 60)
    say("הסקריפט ישאל אותך על כל מפתח בנפרד וישמור הכול בקובץ ‎.env‎")
    say("(הקובץ נשאר רק על המחשב שלך ולא עולה ל-git). אפשר לעצור בכל רגע עם ‎Ctrl+C‎.")

    values = dict(DEFAULTS)
    values.update(read_env())
    total = len(PROMPTS) + 1
    step = 0

    # Telegram token + chat id
    step += 1
    header(step, total, PROMPTS[0]["title"])
    while True:
        values["TELEGRAM_BOT_TOKEN"] = prompt_value(PROMPTS[0], values.get("TELEGRAM_BOT_TOKEN"))
        username = verify_bot(values["TELEGRAM_BOT_TOKEN"])
        if username is False:
            values.pop("TELEGRAM_BOT_TOKEN", None)
            say("  נסי להקליד את הטוקן שוב.")
            continue
        if username:
            values["TELEGRAM_BOT_USERNAME"] = username
        break
    write_env(values)

    step += 1
    header(step, total, "‏Telegram chat ID (אוטומטי)")
    existing_chat = values.get("TELEGRAM_CHAT_ID")
    if existing_chat and not ask_yes_no("  כבר שמור chat ID. לזהות מחדש?", default=False):
        say("  ← נשאר ה-chat ID הקיים.")
    else:
        while True:
            chat_id = find_chat_id(values["TELEGRAM_BOT_TOKEN"], values.get("TELEGRAM_BOT_USERNAME", ""))
            if chat_id:
                values["TELEGRAM_CHAT_ID"] = chat_id
                break
            if ask_yes_no("  לנסות שוב?", default=True):
                continue
            manual = input("  אפשר להקליד chat ID ידנית (או Enter לדלג): ").strip()
            if manual:
                values["TELEGRAM_CHAT_ID"] = manual
            break
    write_env(values)

    # Supabase + Claude
    for item in PROMPTS[1:]:
        step += 1
        header(step, total, item["title"])
        values[item["key"]] = prompt_value(item, values.get(item["key"]))
        write_env(values)

    say()
    say("=" * 60)
    missing = [k for k in ENV_KEYS if not values.get(k)]
    if missing:
        say("  ⚠ נשמר, אבל חסרים: " + ", ".join(missing))
        say("  אפשר להריץ את הסקריפט שוב כדי להשלים.")
    else:
        say("  ✅ הכול נשמר בקובץ ‎.env‎")
    say()
    say("  עכשיו חזרי ל-Claude Code וכתבי: סיימתי")
    say("=" * 60)


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        say()
        say("  הופסק. מה שכבר הוקלד נשמר ב-‎.env‎ — אפשר להריץ שוב ולהמשיך.")
        sys.exit(1)
